# Generated by Django 4.1.3 on 2022-11-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_fed_mouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='cohortDisplayName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fed',
            name='fedDisplayName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='genotype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='mouseDisplayName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='study',
            name='studyDisplayName',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='FedDataRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actTimestamp', models.DateTimeField()),
                ('deviceNumber', models.CharField(max_length=10)),
                ('batteryVol', models.CharField(max_length=10)),
                ('motorTurns', models.CharField(max_length=5)),
                ('sessionType', models.CharField(max_length=20)),
                ('event', models.IntegerField(default=0)),
                ('activePoke', models.IntegerField(default=0)),
                ('leftPokeCount', models.IntegerField(default=0)),
                ('rightPokeCount', models.IntegerField(default=0)),
                ('pelletCount', models.IntegerField(default=0)),
                ('retrievalTime', models.IntegerField(default=0)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mouse')),
            ],
        ),
    ]
