# Generated by Django 4.1.3 on 2022-11-24 19:36

from django.db import migrations
from datetime import datetime
from auto.models import Study

def init_fake_study(apps, schema_editor):

    s = Study(studyDisplayName="pseustudy", studyDesc="", startDate=datetime.now(), endDate=datetime.now())
    s.save()
    #c = Corhort()

class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_cohort_cohortdisplayname_and_more'),
    ]

    operations = [
        migrations.RunPython(init_fake_study),
    ]
