# Generated by Django 4.1.3 on 2022-11-24 19:50

from django.db import migrations
from datetime import datetime
from auto.models import Study, Cohort, Mouse, Fed

def init_fake_mouse(apps, schema_editor):
    s = Study.objects.get(pk=1)
    c = Cohort(cohortDisplayName="pseucohort", cohortDesc="", startDate=datetime.now(), endDate=datetime.now(), study=s)
    c.save()
    fed = Fed(fedDisplayName="pseufed", cohort=c)
    fed.save()
    m = Mouse(mouseDisplayName="pseumouse",genotype="", sex=0, dob=datetime.now(), fed=fed)
    m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20221124_1936'),
    ]

    operations = [
        migrations.RunPython(init_fake_mouse),
    ]
