# Generated by Django 4.1.3 on 2022-11-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_20221124_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedDataByHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftPokeCount', models.IntegerField(default=0)),
                ('rightPokeCount', models.IntegerField(default=0)),
                ('pelletCount', models.IntegerField(default=0)),
                ('activePoke', models.IntegerField(default=0)),
                ('pokeAcc', models.DecimalField(decimal_places=6, default=0.0, max_digits=7)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('numHour', models.IntegerField(default=0)),
                ('fedDate', models.DateTimeField()),
                ('fedDaySinceCohortStart', models.IntegerField(default=0)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mouse')),
            ],
        ),
        migrations.CreateModel(
            name='FedDataByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftPokeCount', models.IntegerField(default=0)),
                ('rightPokeCount', models.IntegerField(default=0)),
                ('pelletCount', models.IntegerField(default=0)),
                ('activePoke', models.IntegerField(default=0)),
                ('pokeAcc', models.DecimalField(decimal_places=6, default=0.0, max_digits=7)),
                ('fedDate', models.DateTimeField()),
                ('fedDaySinceCohortStart', models.IntegerField(default=0)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mouse')),
            ],
        ),
    ]
