# Generated by Django 4.1.3 on 2022-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_feddatabyhour_feddatabyday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feddatabyday',
            name='fedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feddatabyhour',
            name='fedDate',
            field=models.DateField(),
        ),
    ]
