# Generated by Django 4.1.3 on 2022-11-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_alter_feddatabyday_feddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='study',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='study',
            name='startDate',
            field=models.DateField(),
        ),
    ]
