# Generated by Django 4.1.3 on 2022-11-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_remove_feddatabyday_feddaysincecohortstart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedDataRolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeAcc', models.DecimalField(decimal_places=6, default=0.0, max_digits=7)),
                ('windowSize', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('fedDate', models.DateField()),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mouse')),
            ],
        ),
    ]
