# Generated by Django 4.1.3 on 2022-12-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_feddataraw_actnumday'),
    ]

    operations = [
        migrations.AddField(
            model_name='feddatabyday',
            name='fedNumDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyhour',
            name='fedNumDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatarolling',
            name='fedNumDay',
            field=models.IntegerField(default=0),
        ),
    ]
