# Generated by Django 4.1.3 on 2022-12-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_feddatabyday_fednumday_feddatabyhour_fednumday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedDataTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testType', models.CharField(max_length=10)),
                ('fedNumDay', models.IntegerField(default=0)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mouse')),
            ],
        ),
    ]
