# Generated by Django 4.1.3 on 2023-06-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0016_feddatabyrt'),
    ]

    operations = [
        migrations.AddField(
            model_name='feddatabyday',
            name='rtAvg',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='feddatabyday',
            name='rtPelletCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyday',
            name='rtSem',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
    ]
