# Generated by Django 4.1.3 on 2023-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0017_feddatabyday_rtavg_feddatabyday_rtpelletcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feddatabyday',
            name='rtAvg',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feddatabyday',
            name='rtSem',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
