# Generated by Django 4.1.3 on 2023-06-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0018_alter_feddatabyday_rtavg_alter_feddatabyday_rtsem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feddatabyday',
            name='rtRaw',
            field=models.TextField(default=''),
        ),
    ]
