# Generated by Django 4.1.3 on 2023-06-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0019_feddatabyday_rtraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='feddatarolling',
            name='curPoke',
            field=models.IntegerField(default=0),
        ),
    ]
