# Generated by Django 4.1.3 on 2023-06-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0020_feddatarolling_curpoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feddatarolling',
            name='curPoke',
        ),
    ]
