# Generated by Django 4.1.3 on 2023-06-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0021_remove_feddatarolling_curpoke'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedDataRollingPoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curPoke', models.IntegerField(default=0)),
                ('windowSize', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('fedDate', models.DateField()),
                ('fedNumDay', models.IntegerField(default=0)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mouse')),
            ],
        ),
    ]
