# Generated by Django 4.1.3 on 2023-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0022_feddatarollingpoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feddataraw',
            name='motorTurns',
            field=models.CharField(max_length=10),
        ),
    ]
