# Generated by Django 4.1.3 on 2024-05-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0023_alter_feddataraw_motorturns'),
    ]

    operations = [
        migrations.AddField(
            model_name='feddatabyday',
            name='leftDuringDispenseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyday',
            name='leftWithPelletCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyday',
            name='rightDuringDispenseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyday',
            name='rightWithPelletCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyhour',
            name='leftDuringDispenseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyhour',
            name='leftWithPelletCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyhour',
            name='rightDuringDispenseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feddatabyhour',
            name='rightWithPelletCount',
            field=models.IntegerField(default=0),
        ),
    ]
